### ISSUE TITLE
Crashing Example Program

### ISSUE THREAD

**Issue by OxyDeadbeef** [tomaka/android-rs-glue#59]
When I try to compile the example program and run it on my phone it starts up and then crashes right away.  Also, after it says `success` it prints `rm failed for -f, No such file or directory`.  I'm not sure why a simple example program would crash - does it work on other machines?

**Comment by OxyDeadbeef** [comment]
By running `git diff` I found
`
- "android_glue 0.0.1",
+ "android_glue 0.0.2",
`
in the file examples/Cargo.lock.  It seems as though the example was not tested since the last update of android-rs.  That answers my question of why an example program would crash, but it would be nice if someone updated the example program.

**Comment by tomaka** [comment]
Ah, thanks for finding this.

**Comment by OxyDeadbeef** [comment]
Using Logcat I was able to find this error at the crash:
`E/AndroidRuntime( 8199): FATAL EXCEPTION: main`
`E/AndroidRuntime( 8199): java.lang.RuntimeException: Unable to start activity` `ComponentInfo{com.example.native_activity/android.app.NativeActivity}:` `java.lang.IllegalArgumentException: Unable to load native library: /data/data/com.example.native_activity/lib/libmain.so`
`E/AndroidRuntime( 8199): 	at android.app.ActivityThread.main(ActivityThread.java:4795)`
`E/AndroidRuntime( 8199): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)`
`E/AndroidRuntime( 8199): 	at dalvik.system.NativeStart.main(Native Method)`
`E/AndroidRuntime( 8199): Caused by: java.lang.IllegalArgumentException: Unable to load native library: /data/data/com.example.native_activity/lib/libmain.so`

**Comment by OxyDeadbeef** [comment]
By adding to the java automatically `System.loadLibrary("main");` It changed the logcat error to `java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1306]:   138 cannot locate 'dl_iterate_phdr`

**Comment by OxyDeadbeef** [comment]
It seems to be some problem with linking, but I can't figure out what's causing the problem ( Spent the whole day trying to figure it out).  Do you have any Ideas @tomaka ?
