### ISSUE TITLE
openjdk-8

### ISSUE THREAD

**Issue by ozkriff** [tomaka/android-rs-glue#74]
Looks like android sdk now requires openjdk-8.

I had problems few days ago with android build because of it:

```
$ make android
cargo build --target arm-linux-androideabi --release -j 1
   Compiling zoc v0.0.1 (file:///home/ozkriff/zoc/main)
error: linking with `/home/ozkriff/zoc/main/deps/android-rs-glue/apk-builder/target/debug/apk-builder` failed: exit code: 1
note: "/home/ozkriff/zoc/main/deps/android-rs-glue/apk-builder/target/debug/apk-builder" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-Wl,--allow-multiple-definition" "-L" "/usr/local/lib/rustlib/arm-linux-androideabi/lib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/zoc.0.o" "-o" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/zoc" "-Wl,--gc-sections" "-pie" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release" "-L" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps" "-L" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/build/miniz-sys-d03126dbc9ee0074/out" "-L" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/build/stb_tt-b704d4f9419eec86/out" "-L" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/build/stb_tt-b704d4f9419eec86/out" "-L" "/usr/local/lib/rustlib/arm-linux-androideabi/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libvisualizer-258e69740ecc8bac.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libcore-d046c1c0215ee931.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libcollision-cd3812bdb85c8ccf.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libglutin-a61a66b0e0f47240.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libzgl-87e2c1e7331c6e87.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libcommon-8a715008850e5692.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libandroid_glue-3ce65602f8f4be54.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libimage-f8c7ba4adad7f6fb.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libbyteorder-bff578a6925be5fe.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libenum_primitive-2dc0d7f5a40461af.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libzoc_gl-55af1af8d24f954a.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libtime-22c21fe32894ddad.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libpng-488d1ce4b6bdca94.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libinflate-2fe25b73bec31191.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libflate2-3d7b836197e354ce.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libminiz_sys-d03126dbc9ee0074.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libbitflags-646076c1f4684754.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libcgmath-1aaf8f45781c2a5a.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libnum-d3b232b2ec3de579.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/librand-6fab17fc670a2bc8.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/librustc_serialize-79a17eda1cd94e46.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libstb_tt-b704d4f9419eec86.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/liblibc-dd3420cb049117bb.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/libshared_library-1424319f6da054d2.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/liblibc-c1044b0a546bbfd6.rlib" "/home/ozkriff/zoc/main/target/arm-linux-androideabi/release/deps/liblazy_static-007034d2ad8108ce.rlib" "/usr/local/lib/rustlib/arm-linux-androideabi/lib/libstd-9026086f.rlib" "/usr/local/lib/rustlib/arm-linux-androideabi/lib/libcollections-9026086f.rlib" "/usr/local/lib/rustlib/arm-linux-androideabi/lib/liballoc-9026086f.rlib" "/usr/local/lib/rustlib/arm-linux-androideabi/lib/liballoc_jemalloc-9026086f.rlib" "/usr/local/lib/rustlib/arm-linux-androideabi/lib/liblibc-9026086f.rlib" "/usr/local/lib/rustlib/arm-linux-androideabi/lib/librand-9026086f.rlib" "/usr/local/lib/rustlib/arm-linux-androideabi/lib/librustc_unicode-9026086f.rlib" "/usr/local/lib/rustlib/arm-linux-androideabi/lib/libcore-9026086f.rlib" "-l" "android" "-l" "EGL" "-l" "GLESv2" "-l" "android" "-l" "log" "-l" "android" "-l" "stb_truetype" "-l" "c" "-l" "m" "-l" "dl" "-l" "log" "-l" "gcc" "-l" "gcc" "-l" "c" "-l" "m" "-l" "compiler-rt"
note:
BUILD FAILED
/home/ozkriff/rust/android-sdk-linux/tools/ant/build.xml:888: The following error occurred while executing this line:
/home/ozkriff/rust/android-sdk-linux/tools/ant/build.xml:890: The following error occurred while executing this line:
/home/ozkriff/rust/android-sdk-linux/tools/ant/build.xml:902: The following error occurred while executing this line:
/home/ozkriff/rust/android-sdk-linux/tools/ant/build.xml:283: null returned: 1

Total time: 1 second
Buildfile: /tmp/android-rs-glue-rust-to-apk.GULXf5uNjRh6/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 24.4.1
 [checkenv] Installed at /home/ozkriff/rust/android-sdk-linux

-setup:
     [echo] Project Name: rust-android
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 24.0.0 rc1
     [echo] Resolving Build Target for rust-android...
[gettarget] Project Target:   Android 5.0.1
[gettarget] API level:        21
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /tmp/android-rs-glue-rust-to-apk.GULXf5uNjRh6/res
    [mkdir] Created dir: /tmp/android-rs-glue-rust-to-apk.GULXf5uNjRh6/bin
    [mkdir] Created dir: /tmp/android-rs-glue-rust-to-apk.GULXf5uNjRh6/bin/res
    [mkdir] Created dir: /tmp/android-rs-glue-rust-to-apk.GULXf5uNjRh6/bin/rsObj
    [mkdir] Created dir: /tmp/android-rs-glue-rust-to-apk.GULXf5uNjRh6/bin/rsLibs
    [mkdir] Created dir: /tmp/android-rs-glue-rust-to-apk.GULXf5uNjRh6/gen
    [mkdir] Created dir: /tmp/android-rs-glue-rust-to-apk.GULXf5uNjRh6/bin/classes
    [mkdir] Created dir: /tmp/android-rs-glue-rust-to-apk.GULXf5uNjRh6/bin/dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for rust-android...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency]
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...
   [subant] No sub-builds to iterate on

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 1 source file to /tmp/android-rs-glue-rust-to-apk.GULXf5uNjRh6/bin/classes

-post-compile:

-obfuscate:

-dex:
      [dex] input: /tmp/android-rs-glue-rust-to-apk.GULXf5uNjRh6/bin/classes
      [dex] Converting compiled files and external libraries into /tmp/android-rs-glue-rust-to-apk.GULXf5uNjRh6/bin/classes.dex...
       [dx] Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0
       [dx]     at java.lang.ClassLoader.defineClass1(Native Method)
       [dx]     at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
       [dx]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       [dx]     at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
       [dx]     at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
       [dx]     at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
       [dx]     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
       [dx]     at java.security.AccessController.doPrivileged(Native Method)
       [dx]     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
       [dx]     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
       [dx]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
       [dx]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
       [dx]     at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Error while executing program `ant` debug, or missing program.

error: aborting due to previous error
Could not compile `zoc`.

To learn more, run the command again with --verbose.
make: *** [android] Error 101
$
```

"Unsupported major.minor version 52.0" -
http://stackoverflow.com/questions/23249331/java-unsupported-major-minor-version-52-0

**Comment by mattico** [comment]
I had the same problem, and solved it by installing `openjdk-8-jdk`.
